version: "3.8"
services:
  devcontainer:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ..
    volumes:
      - ..:/workspaces/dansdata/api:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgis/postgis:15-master
    restart: unless-stopped
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: verceldb
    ports:
      - 5432:5432
    volumes:
      - dansdata-db-data:/var/lib/postgresql/data

volumes:
  dansdata-db-data:
