version: "3.8"
services:
  api:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ..
    volumes:
      - ..:/workspaces/dansdata/api:cached
    command: sleep infinity
    networks:
      - dansdata-net

  api-db:
    build:
      context: ../database
    restart: unless-stopped
    networks:
      - dansdata-net
    volumes:
      - dansdata-api-db-data:/var/lib/postgresql/data

networks:
  dansdata-net:
    driver: bridge

volumes:
  dansdata-api-db-data:
