name: Lint and Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: ubuntu

    env:
      VERCEL_GIT_COMMIT_REF: ${{ github.head_ref || github.ref_name }}
      VERCEL_GIT_COMMIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Verify Code Formatting
        run: npm run lint

      - name: Test
        run: npm run test:all
