name: Lint and Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: ubuntu

    env:
      VERCEL_GIT_COMMIT_REF: ${{ github.head_ref || github.ref_name }}
      VERCEL_GIT_COMMIT_SHA: ${{ github.sha }}

    services:
      api-db:
        image: postgis/postgis:15-master
        env:
          POSTGRES_USER: default
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: verceldb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Verify Code Formatting
        run: npm run lint

      - name: Push Database Schema to Postgres
        run: npm run dev:db:push

      - name: Test
        run: npm run test:all
